apiVersion: hive.openshift.io/v1
kind: HiveConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "7"
  name: hive
  namespace: open-cluster-management
spec:
  featureGates:
    custom:
      enabled:
      - AlphaAgentInstallStrategy
    featureSet: Custom
  logLevel: {{ .Values.spec.logLevel }}
  targetNamespace: hive