apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
  name: rhacm-operator-group
  namespace: open-cluster-management
spec:
  targetNamespaces:
    - open-cluster-management