apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "10"
  name: assisted-deployment-pull-secret
  namespace: open-cluster-management
stringData:
  .dockerconfigjson: '{"auths":{"cloud.openshift.com":{"auth":"Zm9vOmJhcg==","email":"test@example.com"},"quay.io":{"auth":"Zm9vOmJhcg==","email":"test@example.com"},"registry.connect.redhat.com":{"auth":"Zm9vOmJhcg==","email":"test@example.com"},"registry.redhat.io":{"auth":"Zm9vOmJhcg==","email":"test@example.com"},"registry.domain.example.com:5000":{"auth":"Zm9vOmJhcg==","email":"test@example.com"}}}'