apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
  name: sriov-fec-operator-group
  namespace: vran-acceleration-operators
spec:
  targetNamespaces:
    - vran-acceleration-operators