apiVersion: sriovnetwork.openshift.io/v1
kind: SriovOperatorConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "10"
  name: default
  namespace: openshift-sriov-network-operator
spec:
  configDaemonNodeSelector:
    node-role.kubernetes.io/master: ""
  disableDrain: {{ .Values.spec.disableDrain }}
  enableInjector: {{ .Values.spec.enableInjector }}
  enableOperatorWebhook: {{ .Values.spec.enableOperatorWebhook }}