apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
  name: "local-disks"
  namespace: "openshift-local-storage"
spec:
  managementState: Managed
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: cluster.ocs.openshift.io/openshift-storage
          operator: Exists
  storageClassDevices:
    - storageClassName: "lso-sc"
      volumeMode: Block
      devicePaths:
        - {{ .Values.spec.storageClassDevices.devicePaths }}