apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cu-pao
  namespace: openshift-gitops
spec:
  generators:
  - list:
      # Parameters are generated based on this cluster list, to be substituted
      # into the template below.
      elements:
      - cluster: cu-compact-1
        url: https://kubernetes.default.svc
  template:
    # An Argo CD Application template, with support for parameter substitution
    # with values from parameters generated above.
    metadata:
      name: '{{cluster}}-cu-pao'
    spec:
      project: default
      source:
        repoURL: https://github.com/vhernandomartin/gitops-blueprints-orchestration.git
        targetRevision: HEAD
        path: resources/operators/openshift-performance-addon-operator
        helm:
          valueFiles:
            - values-cu.yaml
      destination:
        server: '{{url}}'
        namespace: openshift-performance-addon-operator
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true