spec:
  cpu:
    isolated: 2-31,34-63
    reserved: 0-1,32-33
  hugepages:
    defaultHugepagesSize: 1G
    pages:
      count: 20
      size: 1G
  net:
    userLevelNetworking: true
  numa:
    topologyPolicy: restricted
  realTimeKernel:
    enabled: false